const COMMON_WORDS = [
  "abandon", "ability", "able", "about", "above", "absent", "absolute",
  "accept", "access", "accident", "account", "achieve", "acknowledge",
  "acquire", "across", "action", "active", "activity", "actual", "adapt",
  "address", "admire", "admit", "adopt", "advance", "advantage", "adventure",
  "advice", "affect", "afford", "after", "again", "age", "agree", "ahead",
  "allow", "almost", "alone", "along", "already", "although", "always",
  "amount", "ancient", "anger", "animal", "announce", "annual", "another",
  "answer", "anyone", "anything", "anyway", "apart", "apparent", "appeal",
  "appear", "apple", "apply", "appoint", "approach", "approve", "area",
  "argue", "arise", "arrange", "arrive", "article", "artist", "aspect",
  "assault", "assess", "assign", "assist", "assume", "assure", "attach",
  "attack", "attempt", "attend", "attract", "auction", "audience", "author",
  "beautiful", "become", "before", "begin", "behave", "behind", "believe",
  "belong", "benefit", "beside", "better", "beyond", "billion", "blanket",
  "blessing", "blind", "block", "blood", "board", "boast", "bonus",
  "border", "borrow", "bother", "bottle", "bottom", "bounce", "branch",
  "brave", "breath", "bridge", "bright", "broken", "browse", "bubble",
  "burden", "burial", "butter", "button", "camera", "cancel", "canvas",
  "capable", "capital", "capture", "career", "careful", "carrier", "casual",
  "catalog", "caution", "ceiling", "central", "century", "certain",
  "chamber", "champion", "chance", "change", "channel", "chapter",
  "charity", "charter", "choice", "circle", "circus", "citizen", "civil",
  "claim", "classic", "client", "climate", "clinic", "cloth", "coastal",
  "coffee", "collect", "college", "colony", "column", "combat", "combine",
  "comedy", "comfort", "command", "comment", "commit", "common", "company",
  "compare", "compel", "compete", "complex", "comply", "compose", "concept",
  "concern", "conduct", "confirm", "conquer", "consist", "consult",
  "contact", "contain", "contend", "contest", "context", "control",
  "convert", "convey", "convict", "cooking", "correct", "council", "count",
  "country", "courage", "course", "cousin", "cover", "crack",
  "craft", "crash", "create", "credit", "crisis", "critic", "crucial",
  "culture", "current", "custom", "damage", "danger", "debate", "decade",
  "decide", "declare", "decline", "decree", "deduct", "defeat", "defend",
  "define", "degree", "delay", "delight", "deliver", "demand", "demise",
  "denial", "depart", "depend", "depict", "deploy", "deposit", "deprive",
  "derive", "desert", "design", "desire", "despite", "destiny", "destroy",
  "detail", "detain", "detect", "develop", "device", "devote", "differ",
  "dinner", "direct", "dismiss", "display", "dispute", "distant", "distinct",
  "diverse", "divide", "divine", "doctor", "dollar", "domain", "domestic",
  "donate", "double", "doubt", "dozen", "draft", "dragon", "drama",
  "drastic", "drawer", "dream", "dress", "drift", "driven", "driver",
  "during", "dynamic", "eager", "earlier", "eastern", "economy", "edition",
  "educate", "effort", "elected", "elegant", "element", "embrace", "emerge",
  "emotion", "emperor", "emphasize", "empire", "employ", "enable", "enact",
  "endless", "endorse", "endure", "energy", "enforce", "engage", "engine",
  "enhance", "enjoy", "enlarge", "enlist", "enrich", "ensure", "enter",
  "entire", "entity", "entrance", "envelope", "episode", "equal", "equip",
  "escape", "essence", "estate", "eternal", "ethical", "evaluate", "evening",
  "evident", "exactly", "examine", "example", "exceed", "excellent",
  "except", "excerpt", "excess", "exchange", "excite", "exclude", "excuse",
  "execute", "exempt", "exercise", "exhaust", "exhibit", "exist", "expand",
  "expect", "expense", "expert", "expire", "explain", "exploit", "explore",
  "express", "extend", "extent", "extract", "extreme", "fabric", "facial",
  "factor", "faculty", "fading", "failure", "fairly", "falcon", "fallen",
  "falsify", "family", "famous", "fancy", "fantasy", "fashion", "fatal",
  "fatigue", "feature", "federal", "feeling", "fiction", "fierce", "figure",
  "filter", "final", "finance", "finding", "finger", "finish", "fiscal",
  "fixing", "flavor", "fleece", "flexible", "flight", "floating", "flourish",
  "flower", "follow", "forbid", "forced", "forest", "forever", "forgive",
  "formal", "format", "former", "fortune", "foster", "founder", "fraction",
  "fragile", "frank", "fraud", "freedom", "french", "frequent", "friend",
  "frozen", "future", "gadget", "gallery", "gambit", "garden", "garment",
  "gather", "gender", "general", "genetic", "genius", "gentle", "genuine",
  "gesture", "giant", "gifted", "global", "golden", "govern", "graceful",
  "gradual", "grant", "graphic", "grateful", "gravity", "greater", "grocery",
  "ground", "growth", "guarantee", "guard", "guess", "guidance", "guilty",
  "habitat", "halfway", "hammer", "handful", "handle", "happen", "harbor",
  "harden", "harmony", "harvest", "hazard", "health", "hearing", "heaven",
  "heavily", "height", "helpful", "heroic", "hidden", "highway", "hiking",
  "history", "holder", "honest", "honor", "horizon", "horror", "hostile",
  "house", "humble", "humor", "hybrid", "iconic", "ideally", "ignore",
  "illegal", "illness", "image", "imagine", "immense", "immunity", "impact",
  "implant", "import", "impose", "improve", "impulse", "incident", "income",
  "increase", "indeed", "indicate", "indoor", "induce", "industry",
  "infancy", "infect", "infer", "infinite", "influence", "inform",
  "inhabit", "inherit", "initial", "inject", "injure", "inmate", "inner",
  "inquiry", "insect", "insert", "inside", "insight", "inspect", "install",
  "instant", "instinct", "insult", "insure", "intact", "intake", "integrate",
  "intense", "intent", "interact", "interest", "internal", "interval",
  "intervene", "intimate", "invade", "invent", "invest", "invite", "involve",
  "isolate", "joint", "journal", "journey", "joyful", "judge", "juice",
  "jungle", "junior", "jurist", "justice", "justify", "keenly", "keeper",
  "kernel", "killer", "kindly", "kingdom", "kitten", "knock", "knowledge",
  "label", "labor", "landing", "landlord", "landscape", "largest", "latent",
  "launch", "laundry", "lawful", "lawyer", "layout", "leader", "league",
  "learning", "leather", "legacy", "legal", "legend", "legislate", "legitimate",
  "leisure", "length", "lesson", "letter", "level", "liable", "liberal",
  "liberty", "library", "license", "likely", "likewise", "limit", "linear",
  "linen", "linkage", "liquid", "listen", "literal", "literary", "little",
  "living", "lobby", "local", "locate", "logical", "lonely", "longing",
  "loosen", "lovely", "loyalty", "lucky", "luxury", "machine", "magazine",
  "magic", "magnetic", "majesty", "manage", "mandate", "mansion", "manual",
  "marble", "margin", "marine", "market", "marriage", "martial", "massive",
  "master", "match", "material", "matter", "mature", "maximum", "meaning",
  "measure", "mechanic", "mediate", "medical", "medium", "member", "memory",
  "mental", "mentor", "merchant", "mercy", "merely", "merger", "merit",
  "method", "mighty", "migrant", "military", "million", "mineral", "minimal",
  "minimum", "mining", "minister", "minor", "miracle", "mirror", "misery",
  "mission", "mistake", "mixture", "mobile", "moderate", "modern", "modest",
  "modify", "module", "moisture", "moment", "monarch", "monitor", "monopoly",
  "monster", "monthly", "monument", "moral", "moreover", "mortal",
  "mortgage", "motion", "motivate", "motor", "mountain", "movement",
  "murder", "muscle", "museum", "musical", "mutual", "mystery", "mythical",
  "narrow", "nation", "native", "natural", "nature", "navigate", "nearby",
  "nearly", "neatly", "necessary", "needle", "negate", "negative", "neglect",
  "neighbor", "neither", "nervous", "network", "neutral", "never", "nevertheless",
  "noble", "nobody", "normal", "normally", "northern", "notable", "notice",
  "notion", "novel", "nowhere", "nuclear", "number", "numerous", "nursing",
  "object", "oblige", "obscure", "observe", "obtain", "obvious", "occupy",
  "offense", "offer", "officer", "official", "offspring", "online", "opinion",
  "opponent", "oppose", "option", "orange", "orbit", "orchard", "orchestra",
  "order", "organ", "organic", "orient", "origin", "ornament", "outbreak",
  "outcome", "outdoor", "outer", "outlet", "outline", "output", "outrage",
  "outside", "outstanding", "overall", "overcome", "overlook", "overseas",
  "overturn", "overwhelm", "owner", "oxygen", "packet", "painful", "paint",
  "palace", "pamphlet", "panel", "panic", "parade", "parent", "partial",
  "particle", "partner", "passage", "passion", "passive", "passport",
  "patent", "patience", "pattern", "pause", "payment", "peaceful", "peasant",
  "penalty", "pension", "people", "perceive", "perfect", "perform",
  "perhaps", "period", "permanence", "permit", "persist", "person",
  "persuade", "petition", "phenomenon", "philosophy", "phrase", "physical",
  "pillar", "pioneer", "pirate", "pity", "placed", "planet", "plastic",
  "plateau", "player", "please", "pleasure", "pledge", "plenty", "plight",
  "plugin", "plunge", "poem", "poet", "point", "poison", "pole", "police",
  "policy", "polish", "polite", "poor", "popular", "port", "portion",
  "portrait", "position", "positive", "possess", "possible", "postpone",
  "potato", "potential", "pound", "poverty", "powder", "power", "practice",
  "praise", "pray", "preach", "precede", "precious", "precise", "predict",
  "prefer", "premier", "premium", "prepare", "prescribe", "presence", "present",
  "preserve", "president", "press", "pressure", "prestige", "presume",
  "pretend", "prevail", "prevent", "previous", "price", "pride", "primary",
  "prime", "prince", "princess", "principal", "principle", "print", "prior",
  "prison", "privacy", "private", "prize", "probably", "problem", "proceed",
  "process", "produce", "product", "profess", "profit", "program",
  "progress", "project", "prominent", "promise", "promote", "prompt",
  "proof", "proper", "property", "prophet", "proposal", "propose",
  "prospect", "protect", "protest", "proud", "prove", "provide", "province",
  "provision", "provoke", "prune", "psychic", "public", "publish", "pulse",
  "pumpkin", "punch", "punish", "purchase", "pure", "purpose", "pursue",
  "puzzle", "quality", "quantity", "quarter", "queen", "question", "quickly",
  "quiet", "quit", "quite", "quote", "radical", "random", "range", "rapid",
  "rarely", "rating", "ratio", "reach", "react", "reader", "realistic",
  "realize", "reason", "recall", "receive", "recent", "recipe", "reckon",
  "recognize", "recover", "recycle", "reduce", "reform", "refugee",
  "refund", "refuse", "region", "register", "regret", "regulate", "reign",
  "reject", "relate", "relax", "release", "relevant", "relief", "religion",
  "reluctant", "rely", "remain", "remark", "remedy", "remember", "remind",
  "remote", "remove", "render", "rent", "repair", "repeat", "replace",
  "reply", "report", "republic", "reputable", "request", "require",
  "rescue", "resemble", "reserve", "reside", "resign", "resist", "resolve",
  "resource", "respect", "respond", "restore", "result", "resume", "retail",
  "retain", "retire", "retreat", "return", "reveal", "revenue", "reverse",
  "review", "revise", "revive", "revolt", "reward", "rhythm", "ribbon",
  "riddle", "rights", "rigid", "riot", "rising", "rival", "robin",
  "robust", "rocket", "romance", "rotate", "rough", "rountine", "royal",
  "rubber", "ruined", "ruling", "runner", "rural", "sacred", "sacrifice",
  "safety", "sailor", "saint", "salary", "salmon", "sample", "sanction",
  "sanctuary", "satellite", "satisfy", "sauce", "saving", "scale", "scan",
  "scandal", "scatter", "scenario", "schedule", "scheme", "scholar",
  "school", "science", "scope", "score", "scratch", "screen", "script",
  "season", "second", "secret", "section", "sector", "secure", "seed",
  "segment", "select", "senior", "sense", "sensitive", "sentence", "sentiment",
  "separate", "sequence", "serial", "series", "serious", "servant", "serve",
  "service", "session", "settle", "setup", "severe", "shadow", "shaft",
  "shallow", "shame", "shape", "share", "shelter", "shield", "shift",
  "shining", "shirt", "shock", "shoot", "shoulder", "shout", "shower",
  "sibling", "sickness", "signal", "silence", "silver", "similar", "simple",
  "simply", "sincere", "single", "sister", "situate", "sketch", "skilled",
  "sleep", "slight", "slip", "slogan", "slope", "smart", "smooth", "snap",
  "snow", "social", "society", "sodium", "soften", "solar", "soldier",
  "sole", "solemn", "solid", "solution", "solvent", "somehow", "somewhat",
  "sooner", "sorrow", "sort", "source", "sovereign", "spacious", "spare",
  "spark", "spatial", "speaker", "special", "species", "specific", "specify",
  "speech", "speed", "spelling", "sphere", "spider", "spirit", "spite",
  "splendid", "spoken", "sponsor", "spoon", "sport", "spouse", "spread",
  "spring", "square", "stable", "staff", "stage", "stain", "stair",
  "stake", "stale", "stall", "stamp", "stance", "standard", "standing",
  "staple", "star", "stare", "stark", "start", "starve", "state", "static",
  "statue", "status", "statute", "steady", "steal", "steam", "steel",
  "steep", "steer", "stellar", "sticky", "stiff", "still", "stimulus",
  "stir", "stitch", "stock", "stomach", "stone", "storm", "story",
  "straight", "strain", "strange", "strategy", "stream", "street", "strength",
  "stretch", "strict", "stride", "strike", "string", "strip", "stroke",
  "strong", "struggle", "student", "studio", "study", "stuff", "stumble",
  "style", "subject", "sublime", "submit", "subset", "substance", "substitute",
  "subtle", "subtract", "suburb", "succeed", "success", "suffer", "sufficient",
  "suffix", "sugar", "suggest", "suicide", "suit", "suite", "summary",
  "summit", "summon", "sunset", "superb", "superior", "supply", "support",
  "suppose", "supreme", "surely", "surface", "surgeon", "surplus", "surprise",
  "surrender", "surround", "survey", "survive", "suspect", "suspend",
  "sustain", "swallow", "swamp", "swap", "swift", "symbol", "sympathy",
  "symptom", "tackle", "tactical", "talent", "target", "tariff", "taste",
  "tattoo", "teach", "tear", "temple", "temporal", "tempt", "tender",
  "tension", "terminal", "terrible", "territory", "terror", "testimony",
  "textile", "texture", "thanks", "theme", "theory", "therapy", "thereby",
  "thermal", "thicken", "thief", "thinking", "thorough", "thought", "thread",
  "threat", "thrive", "throne", "through", "throw", "thrust", "thunder",
  "ticket", "tissue", "title", "toast", "tobacco", "today", "together",
  "tolerate", "tomorrow", "tongue", "torture", "total", "touch", "tough",
  "tourist", "toward", "tower", "track", "tract", "trade", "tradition",
  "traffic", "tragedy", "trail", "train", "trait", "transaction",
  "transfer", "transform", "transit", "transmit", "transport", "trap",
  "trauma", "travel", "treat", "treaty", "tremendous", "trend", "trial",
  "tribal", "tribute", "trick", "trigger", "triumph", "troop", "trophy",
  "trouble", "truck", "truly", "trumpet", "trust", "trustee", "truth",
  "tunnel", "turmoil", "turtle", "tutor", "twice", "twin", "typical",
  "ugly", "ultimate", "umbrella", "unable", "unaware", "unbroken", "uncertain",
  "uncle", "uncover", "undergo", "undermine", "undertake", "uneasy",
  "unfold", "unforeseen", "unhappy", "uniform", "unify", "union", "unique",
  "unit", "unite", "unity", "universal", "universe", "unknown", "unleash",
  "unlikely", "unlock", "unpaid", "unrest", "untrue", "unusual", "update",
  "upgrade", "uphold", "upper", "upright", "upset", "urban", "urge",
  "urgent", "useful", "useless", "utility", "utilize", "utmost", "utter",
  "vacant", "vacuum", "vague", "valid", "valley", "valuable", "value",
  "variable", "vast", "vault", "vector", "vehicle", "venture", "verbal",
  "verdict", "verify", "version", "vertical", "vessel", "veteran",
  "viable", "vibrant", "vicious", "victim", "victory", "video", "view",
  "vigorous", "village", "violate", "violence", "virtual", "virtue",
  "visible", "vision", "visitor", "visual", "vital", "vivid", "vocal",
  "volcano", "volume", "voluntary", "voucher", "voyage", "vulnerable",
  "wage", "wagon", "waiting", "wake", "walk", "wander", "want", "warm",
  "warn", "warrant", "warrior", "wary", "waste", "watch", "water",
  "wave", "wax", "weaken", "wealth", "weapon", "wear", "weave", "weekly",
  "weigh", "weight", "welcome", "welfare", "western", "whisper", "whole",
  "wicket", "widen", "widespread", "width", "willing", "window", "winter",
  "wisdom", "within", "witness", "wonder", "wooden", "worker", "world",
  "worry", "worship", "worthy", "wound", "wrap", "wreck", "write",
  "wrong", "yard", "yield", "young", "yourself", "youth", "zone",
];

export function getWordList(): string[] {
  return COMMON_WORDS;
}
